config/routes.rb
RasterStats::Application.routes.draw do
  resources :operations, only: :index

  resources :rasters do
    resources :operations, only: :show
  end

  devise_for :users

  get 'tiles/:raster_id/:z/:x/:y.png' => 'tiles#show', as: :tile

  root :to => 'rasters#index'

end

app/models/countries.rb
class Countries < ActiveRecord::Base
  attr_accessible :geometry, :iso_a2, :area, :geometry_moll, :area_moll
end

app/models/operation.rb
class Operation
  attr_reader :name, :display_name

  def self.all
    [:avg, :sum, :min, :max].map { |c| new(c) }
  end

  def initialize(name)
    @name = name
    @display_name = name.capitalize
  end

  def to_param
    @name
  end
end

app/models/raster.rb
class Raster < ActiveRecord::Base
  require 'gdal-ruby/gdal'
  require 'builder'
  require 'nokogiri'

  # Resolutions (and percentages) of the rasters generated
  RESOLUTIONS = {high: 100, medium: 50, low: 10}

  attr_accessible :display_name, :source_file, :color_min, :color_max, :zoom_min, :zoom_max

  validates :display_name, uniqueness: true


  def path(filename = 'default', img_extension = false)
    "#{rasters_path}/#{filename}.tif"
  end

  class << self
    def gdal_translate_command
      `which gdal_translate`.delete("\n")
    end

    def gdalwarp_command
      `which gdalwarp`.delete("\n")
    end

    def python_command
      `which python`.delete("\n")
    end
  end

  #TODO: add background jobs
  def create_tile(z, x, y)
    generate_xml
    system "#{self.class.python_command} #{Rails.root.join('lib')}/create_tiles.py --xml #{rasters_path}/style.xml --tiles #{raster_tiles_path} -z #{z} -x #{x} -y #{y}"
  end

  def create_tiles
    generate_xml
    system "#{self.class.python_command} #{Rails.root.join('lib')}/create_tiles.py --xml #{rasters_path}/style.xml --tiles #{raster_tiles_path} --zmin #{zoom_min} --zmax #{zoom_max}"
  end

  private

  def extract_pixel_size
    Gdal::Gdal.open(path).get_geo_transform()[1]
  end

  def extract_min_max_pixel
    Gdal::Gdal.open(path).get_raster_band(1).compute_raster_min_max()
  end

  def rasters_path
    Rails.root.join('lib', 'rasters', self.id.to_s).tap do |dir|
      FileUtils.mkdir_p dir unless File.directory? dir
    end
  end

  def raster_tiles_path
    Rails.root.join('public', 'tiles', self.id.to_s).tap do |dir|
      FileUtils.mkdir_p dir unless File.directory? dir
    end
  end

  def generate_rasters
    system "#{self.class.gdalwarp_command} -dstnodata 0 #{path} #{path('ndata')}"
    system "#{self.class.gdal_translate_command} -of GTiff #{path('ndata')} -co COMPRESS=LZW #{path('high', true)}"
    system "#{self.class.gdal_translate_command} -outsize #{RESOLUTIONS[:medium]}% #{RESOLUTIONS[:medium]}% -of GTiff #{path('ndata')} -co COMPRESS=LZW #{path('medium', true)}"
    system "#{self.class.gdal_translate_command} -outsize #{RESOLUTIONS[:low]}% #{RESOLUTIONS[:low]}% -of GTiff #{path('ndata')} -co COMPRESS=LZW #{path('low', true)}"
  end

  def generate_xml
    builder = Nokogiri::XML::Builder.new do |xml|
      map = xml.Map {
        style = xml.Style {
          xml.Rule {
            raster_symbolizer = xml.RasterSymbolizer {
              raster_colorizer = xml.RasterColorizer {
                stop = xml.stop
                stop['color'] = color_min
                stop['value'] = extract_min_max_pixel[0].to_s

                stop = xml.stop
                stop['color'] = color_max
                stop['value'] = extract_min_max_pixel[1].to_s
              }

              raster_colorizer['default-mode'] = 'linear'
              raster_colorizer['epsilon'] = '0.001'
            }

            raster_symbolizer['opacity'] = '1'
          }
        }
        style['name'] = 'raster'

        layer = xml.Layer {
          xml.StyleName 'raster'
          xml.Datasource {
            parameter = xml.Parameter path('ndata')
            parameter['name'] = 'file'
            parameter = xml.Parameter 'gdal'
            parameter['name'] = 'type'
            parameter = xml.Parameter '1'
            parameter['name'] = 'band'
          }
        }
        layer['name'] = 'raster'
      }

      map['background-color'] = 'steelblue'
      map['srs'] = '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'
    end

    File.open("#{rasters_path}/style.xml", 'w') do |f|
      f.puts builder.to_xml
    end
  end



  # TODO: add background jobs
  after_create do
    if source_file =~ /^https?:\/\//
      system("wget -O #{path} #{source_file}")
    elsif File.file?(source_file)
      system("cp #{source_file} #{path}")
    else
      raise(RuntimeError, "File not found...")
    end

    self.update_attribute(:pixel_size, extract_pixel_size)

    generate_rasters
    create_tiles
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :registerable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable,
    :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  def index
    @operations = Operation.all
    render json: @operations
  end

  def show
    raster = Raster.find(params[:raster_id])
    sats = Statistics.new(raster, params[:id], params[:polygon], false)
    render json: stats.result
  end
end

app/controllers/rasters_controller.rb
class RastersController < ApplicationController
  respond_to :html, :json
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @rasters = Raster.all
    respond_with(@rasters)
  end

  def show
    @raster = Raster.find(params[:id])
    respond_with(@raster)
  end

  def new
    @raster = Raster.new
    respond_with(@raster)
  end

  def edit
    @raster = Raster.find(params[:id])
    respond_with(@raster)
  end

  def create
    @raster = Raster.new(params[:raster])

    if @raster.save
      flash[:notice] = 'Raster was successfully created.'
    end
    respond_with(@raster)
  end

  def update
    @raster = Raster.find(params[:id])
    if @raster.update_attributes(params[:raster])
      flash[:notice] = 'Raster was successfully updated.'
    end
    @raster.create_tiles
    respond_with(@raster)
  end

  def destroy
    @raster = Raster.find(params[:id])
    @raster.destroy
    flash[:notice] = 'Raster was successfully destroyed.'
    respond_with(@raster)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tiles_helper.rb
module TilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>RasterStats</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "RasterStats", root_path, :class => "brand" %>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Rasters", rasters_path %></li>
            <li><%= link_to "Operations", operations_path %></li>
          </ul>
          <ul class="nav pull-right">
            <% if user_signed_in? %>
              <li><%= link_to truncate("Logout #{current_user.email}"), destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert #{name == :error ? "alert-error" : "alert-success" }" do %>
        <a class="close" data-dismiss="alert" href="#">×</a>
        <%= msg %>
      <% end %>
    <% end %>
    <%= yield %>
    <hr>
    <footer>
      <p>&copy; Company 2012</p>
    </footer>
  </div>
</body>
</html>

app/views/rasters/_form.html.erb
<%= simple_form_for(@raster, :defaults => { :input_html => { :class => 'input-xlarge' } }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :display_name %>
    <%= f.input :source_file %>
    <%= f.input :color_min %>
    <%= f.input :color_max %>
    <%= f.input :zoom_min %>
    <%= f.input :zoom_max %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary" %>
  </div>
<% end %>

app/views/rasters/edit.html.erb
<div class="page-header">
  <%= link_to rasters_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to @raster, :class => 'btn btn-primary' do %>
    <i class="icon-info-sign icon-white"></i>
    Show
  <% end %>
  <h1>Editing raster</h1>
</div>

<%= render 'form' %>

app/views/rasters/index.html.erb
<div class="page-header">
  <%= link_to new_raster_path, :class => 'btn btn-primary' do %>
    <i class="icon-plus icon-white"></i>
    New Raster
  <% end %>
  <h1>Listing rasters</h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Display name</th>
      <th>Source file</th>
      <th>Pixel size</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
<% @rasters.each do |raster| %>
    <tr>
      <td><%= raster.display_name %></td>
      <td><%= truncate(raster.source_file) %></td>
      <td><%= raster.pixel_size %></td>
      <td><%= link_to 'Show', raster %></td>
      <td><%= link_to 'Edit', edit_raster_path(raster) %></td>
      <td><%= link_to 'Destroy', raster, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
<% end %>
  </tbody>
</table>

app/views/rasters/new.html.erb
<div class="page-header">
  <%= link_to rasters_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <h1>New raster</h1>
</div>

<%= render 'form' %>

app/views/rasters/show.html.erb
<div class="page-header">
  <%= link_to rasters_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to edit_raster_path(@raster), :class => 'btn btn-primary' do %>
    <i class="icon-pencil icon-white"></i>
    Edit
  <% end %>
  <h1>Listing rasters</h1>
</div>

<dl>
  <dt>Display name:</dt>
  <dd><%= @raster.display_name %></dd>

  <dt>Source file:</dt>
  <dd><%= @raster.source_file %></dd>

  <dt>Pixel size:</dt>
  <dd><%= @raster.pixel_size %></dd>

  <dt>Tiles URL:</dt>
  <dd><%= tile_url(raster_id: @raster, z: 'z', x: 'x', y: 'y') %></dd>

</dl>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Display name</th>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
<% Operation.all.each do |operation| %>
    <tr>
      <td><%= operation.display_name %></td>
      <td><%= operation.name %></td>
      <td><%= link_to 'Calculate', raster_operation_path(@raster, operation, polygon: '{"type": "FeatureCollection","features": [{ "type": "Feature", "id": 0, "properties": { "id": null, "name": 8, "AREA": 7435.85032686457 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -55.199133830905097, 14.166474645080788 ], [ -139.868730478081005, 21.093987098031544 ], [ -166.295907613411686, 80.619279286349169 ], [ -19.022124354384474, 82.671875568704948 ], [ -55.199133830905097, 14.166474645080788 ] ] ] } }]}') %></td>
    </tr>
<% end %>
  </tbody>
</table>